#!/bin/bash

echo '#include "main.h"' > 0-isupper.c
echo '#include "main.h"' > 0-memset.c
echo '#include "main.h"' > 0-strcat.c
echo '#include "main.h"' > 1-isdigit.c
echo '#include "main.h"' > 1-memcpy.c
echo '#include "main.h"' > 1-strncat.c
echo '#include "main.h"' > 100-atoi.c
echo '#include "main.h"' > 2-strchr.c
echo '#include "main.h"' > 2-strlen.c
echo '#include "main.h"' > 2-strncpy.c
echo '#include "main.h"' > 3-islower.c
echo '#include "main.h"' > 3-puts.c
echo '#include "main.h"' > 3-strcmp.c
echo '#include "main.h"' > 3-strspn.c
echo '#include "main.h"' > 4-isalpha.c
echo '#include "main.h"' > 4-strpbrk.c
echo '#include "main.h"' > 5-strstr.c
echo '#include "main.h"' > 6-abs.c
echo '#include "main.h"' > 9-strcpy.c
echo '#include "main.h"' > _putchar.c
